HBOND_DEFINITION
H7 1 ASP GLU
O2 1 SER THR TYR TRP HIS GLN ASN
O3 1 SER THR TYR TRP HIS GLN ASN
END_HBOND_DEFINITION

REQUIREMENT_DEFINITION
1 HBOND H7 1
2 HBOND O2 1
3 HBOND O3 1
END_REQUIREMENT_DEFINITION